name: order_summary
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^8.1.6                 # BLoC for managing app state
  equatable: ^2.0.5                    # Simplified equality comparison for model classes
  # Dependency Injection & Service Locator
  get_it: ^7.7.0

  # Routing and Navigation
  go_router: ^14.2.2                   # Declarative routing management using GoRouter

  syncfusion_flutter_charts: ^27.2.4

  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
  - assets/
  - assets/json/




